name: CI Pipeline

on:
  push:
    branches:
      - main
      - marco
  pull_request:
    branches:
      - main
      - marco

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Construir e rodar os containers com Docker Compose
      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
          sleep 15 # Aguarda os serviços estarem prontos

      # Executar testes no backend
      - name: Run backend tests
        run: |
          docker exec backend pytest
