name: CI Pipeline

on:
  push:
    branches:
      - main
      - marco
  pull_request:
    branches:
      - main
      - marco

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Instalar o Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Construir e rodar os containers com Docker Compose
      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
          sleep 15 # Aguarda os serviços estarem prontos

      # Verificar se o container do backend está em execução
      - name: Check if backend container is running
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' backend)" != "true" ]; then
            echo "Backend container is not running. Exiting.";
            docker-compose logs backend;
            exit 1;
          fi

      # Executar testes no backend
      - name: Run backend tests
        run: |
          docker exec backend pytest